export const countries = [
    { name: "Afrique du Sud", capital: "Pretoria" },
    { name: "Algérie", capital: "Alger" },
    { name: "Angola", capital: "Luanda" },
    { name: "Bénin", capital: "Porto-Novo" },
    { name: "Botswana", capital: "Gaborone" },
    { name: "Burkina Faso", capital: "Ouagadougou" },
    { name: "Burundi", capital: "Gitega" },
    { name: "Cap-Vert", capital: "Praia" },
    { name: "Cameroun", capital: "Yaoundé" },
    { name: "Comores", capital: "Moroni" },
    { name: "République du Congo", capital: "Brazzaville" },
    { name: "République Démocratique du Congo", capital: "Kinshasa" },
    { name: "Côte d'Ivoire", capital: "Yamoussoukro" },
    { name: "Djibouti", capital: "Djibouti" },
    { name: "Égypte", capital: "Le Caire" },
    { name: "Érythrée", capital: "Asmara" },
    { name: "Eswatini", capital: "Mbabane" },
    { name: "Éthiopie", capital: "Addis-Abeba" },
    { name: "Gabon", capital: "Libreville" },
    { name: "Gambie", capital: "Banjul" },
    { name: "Ghana", capital: "Accra" },
    { name: "Guinée", capital: "Conakry" },
    { name: "Guinée-Bissau", capital: "Bissau" },
    { name: "Guinée Équatoriale", capital: "Malabo" },
    { name: "Kenya", capital: "Nairobi" },
    { name: "Lesotho", capital: "Maseru" },
    { name: "Libéria", capital: "Monrovia" },
    { name: "Libye", capital: "Tripoli" },
    { name: "Madagascar", capital: "Antananarivo" },
    { name: "Malawi", capital: "Lilongwe" },
    { name: "Mali", capital: "Bamako" },
    { name: "Maroc", capital: "Rabat" },
    { name: "Mauritanie", capital: "Nouakchott" },
    { name: "Maurice", capital: "Port-Louis" },
    { name: "Mozambique", capital: "Maputo" },
    { name: "Namibie", capital: "Windhoek" },
    { name: "Niger", capital: "Niamey" },
    { name: "Nigéria", capital: "Abuja" },
    { name: "Ouganda", capital: "Kampala" },
    { name: "République Centrafricaine", capital: "Bangui" },
    { name: "Rwanda", capital: "Kigali" },
    { name: "Sao Tomé-et-Principe", capital: "Sao Tomé" },
    { name: "Sénégal", capital: "Dakar" },
    { name: "Seychelles", capital: "Victoria" },
    { name: "Sierra Leone", capital: "Freetown" },
    { name: "Somalie", capital: "Mogadiscio" },
    { name: "Soudan", capital: "Khartoum" },
    { name: "Soudan du Sud", capital: "Djouba" },
    { name: "Tanzanie", capital: "Dodoma" },
    { name: "Tchad", capital: "N'Djaména" },
    { name: "Togo", capital: "Lomé" },
    { name: "Tunisie", capital: "Tunis" },
    { name: "Zambie", capital: "Lusaka" },
    { name: "Zimbabwe", capital: "Harare" }
  ];
  